### ISSUE TITLE
Doesn't compile on 0.5.2 — CommandSender.getDisplayName() is gone

### ISSUE THREAD

**Issue by andrewkm** [nitrado/hytale-plugin-webserver#25]
Doesn't build against the current server (0.5.2) - `CommandSender` doesn't have `getDisplayName()` anymore, just `getUsername()` and `getUuid()`.

```
CodeCreateCommand.java:[36,95] cannot find symbol
  symbol:   method getDisplayName()
  location: interface com.hypixel.hytale.server.core.command.system.CommandSender
```

Only used in `CodeCreateCommand` line 36 - swapping it for `getUsername()` builds fine.
